/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// GuildQueryMetaDto
    /// </summary>
    [DataContract(Name = "GuildQueryMetaDto")]
    public partial class GuildQueryMetaDto
    {
        /// <summary>
        /// Defines JoinApprovalType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum JoinApprovalTypeEnum
        {
            /// <summary>
            /// Enum AUTO for value: AUTO
            /// </summary>
            [EnumMember(Value = "AUTO")]
            AUTO = 1,

            /// <summary>
            /// Enum MANUAL for value: MANUAL
            /// </summary>
            [EnumMember(Value = "MANUAL")]
            MANUAL = 2
        }


        /// <summary>
        /// Gets or Sets JoinApprovalType
        /// </summary>
        [DataMember(Name = "joinApprovalType", EmitDefaultValue = false)]
        public JoinApprovalTypeEnum? JoinApprovalType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GuildQueryMetaDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GuildQueryMetaDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GuildQueryMetaDto" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="country">country.</param>
        /// <param name="joinApprovalType">joinApprovalType.</param>
        /// <param name="limit">limit (required).</param>
        public GuildQueryMetaDto(string name = default(string), string country = default(string), JoinApprovalTypeEnum? joinApprovalType = default(JoinApprovalTypeEnum?), int? limit = default(int?))
        {
            // to ensure "limit" is required (not null)
            if (limit == null)
            {
                throw new ArgumentNullException("limit is a required property for GuildQueryMetaDto and cannot be null");
            }
            this.Limit = limit;
            this.Name = name;
            this.Country = country;
            this.JoinApprovalType = joinApprovalType;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int? Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GuildQueryMetaDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  JoinApprovalType: ").Append(JoinApprovalType).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
