/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// LeaderboardPeriodRecordUpdateReqDto
    /// </summary>
    [DataContract(Name = "LeaderboardPeriodRecordUpdateReqDto")]
    public partial class LeaderboardPeriodRecordUpdateReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardPeriodRecordUpdateReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LeaderboardPeriodRecordUpdateReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardPeriodRecordUpdateReqDto" /> class.
        /// </summary>
        /// <param name="participantId">participantId (required).</param>
        /// <param name="score">score (required).</param>
        public LeaderboardPeriodRecordUpdateReqDto(string participantId = default(string), decimal? score = default(decimal?))
        {
            // to ensure "participantId" is required (not null)
            if (participantId == null)
            {
                throw new ArgumentNullException("participantId is a required property for LeaderboardPeriodRecordUpdateReqDto and cannot be null");
            }
            this.ParticipantId = participantId;
            // to ensure "score" is required (not null)
            if (score == null)
            {
                throw new ArgumentNullException("score is a required property for LeaderboardPeriodRecordUpdateReqDto and cannot be null");
            }
            this.Score = score;
        }

        /// <summary>
        /// Gets or Sets ParticipantId
        /// </summary>
        [DataMember(Name = "participantId", IsRequired = true, EmitDefaultValue = true)]
        public string ParticipantId { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [DataMember(Name = "score", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Score { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LeaderboardPeriodRecordUpdateReqDto {\n");
            sb.Append("  ParticipantId: ").Append(ParticipantId).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
