/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// LeaderboardPeriodRecordParticipantDto
    /// </summary>
    [DataContract(Name = "LeaderboardPeriodRecordParticipantDto")]
    public partial class LeaderboardPeriodRecordParticipantDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardPeriodRecordParticipantDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LeaderboardPeriodRecordParticipantDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardPeriodRecordParticipantDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="isBot">isBot (required).</param>
        /// <param name="name">name.</param>
        /// <param name="profileData">profileData.</param>
        public LeaderboardPeriodRecordParticipantDto(string id = default(string), bool isBot = default(bool), string name = default(string), Dictionary<string, string> profileData = default(Dictionary<string, string>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LeaderboardPeriodRecordParticipantDto and cannot be null");
            }
            this.Id = id;
            this.IsBot = isBot;
            this.Name = name;
            this.ProfileData = profileData;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets IsBot
        /// </summary>
        [DataMember(Name = "isBot", IsRequired = true, EmitDefaultValue = true)]
        public bool IsBot { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ProfileData
        /// </summary>
        [DataMember(Name = "profileData", EmitDefaultValue = false)]
        public Dictionary<string, string> ProfileData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LeaderboardPeriodRecordParticipantDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsBot: ").Append(IsBot).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProfileData: ").Append(ProfileData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
