/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// LeagueDivisionRecordUpdateReqDto
    /// </summary>
    [DataContract(Name = "LeagueDivisionRecordUpdateReqDto")]
    public partial class LeagueDivisionRecordUpdateReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeagueDivisionRecordUpdateReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LeagueDivisionRecordUpdateReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LeagueDivisionRecordUpdateReqDto" /> class.
        /// </summary>
        /// <param name="playerUid">playerUid (required).</param>
        /// <param name="amount">amount (required).</param>
        public LeagueDivisionRecordUpdateReqDto(string playerUid = default(string), decimal? amount = default(decimal?))
        {
            // to ensure "playerUid" is required (not null)
            if (playerUid == null)
            {
                throw new ArgumentNullException("playerUid is a required property for LeagueDivisionRecordUpdateReqDto and cannot be null");
            }
            this.PlayerUid = playerUid;
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for LeagueDivisionRecordUpdateReqDto and cannot be null");
            }
            this.Amount = amount;
        }

        /// <summary>
        /// Gets or Sets PlayerUid
        /// </summary>
        [DataMember(Name = "playerUid", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerUid { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LeagueDivisionRecordUpdateReqDto {\n");
            sb.Append("  PlayerUid: ").Append(PlayerUid).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
