/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// ListResponseChatRoomDtoVoid
    /// </summary>
    [DataContract(Name = "ListResponseChatRoomDtoVoid")]
    public partial class ListResponseChatRoomDtoVoid
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListResponseChatRoomDtoVoid" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListResponseChatRoomDtoVoid() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListResponseChatRoomDtoVoid" /> class.
        /// </summary>
        /// <param name="content">content (required).</param>
        /// <param name="meta">meta.</param>
        public ListResponseChatRoomDtoVoid(Object content = default(Object), Object meta = default(Object))
        {
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for ListResponseChatRoomDtoVoid and cannot be null");
            }
            this.Content = content;
            this.Meta = meta;
        }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public Object Content { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [DataMember(Name = "meta", EmitDefaultValue = false)]
        public Object Meta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListResponseChatRoomDtoVoid {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
