/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// PlayerMailSendReqDto
    /// </summary>
    [DataContract(Name = "PlayerMailSendReqDto")]
    public partial class PlayerMailSendReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerMailSendReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerMailSendReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerMailSendReqDto" /> class.
        /// </summary>
        /// <param name="mail">mail (required).</param>
        /// <param name="expireDaysAfter">expireDaysAfter.</param>
        public PlayerMailSendReqDto(MailDto mail = default(MailDto), int? expireDaysAfter = default(int?))
        {
            // to ensure "mail" is required (not null)
            if (mail == null)
            {
                throw new ArgumentNullException("mail is a required property for PlayerMailSendReqDto and cannot be null");
            }
            this.Mail = mail;
            this.ExpireDaysAfter = expireDaysAfter;
        }

        /// <summary>
        /// Gets or Sets Mail
        /// </summary>
        [DataMember(Name = "mail", IsRequired = true, EmitDefaultValue = true)]
        public MailDto Mail { get; set; }

        /// <summary>
        /// Gets or Sets ExpireDaysAfter
        /// </summary>
        [DataMember(Name = "expireDaysAfter", EmitDefaultValue = false)]
        public int? ExpireDaysAfter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerMailSendReqDto {\n");
            sb.Append("  Mail: ").Append(Mail).Append("\n");
            sb.Append("  ExpireDaysAfter: ").Append(ExpireDaysAfter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
