/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// PlayerActionLogReqDto
    /// </summary>
    [DataContract(Name = "PlayerActionLogReqDto")]
    public partial class PlayerActionLogReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerActionLogReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerActionLogReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerActionLogReqDto" /> class.
        /// </summary>
        /// <param name="eventCode">eventCode (required).</param>
        /// <param name="eventData">eventData (required).</param>
        public PlayerActionLogReqDto(string eventCode = default(string), Object eventData = default(Object))
        {
            // to ensure "eventCode" is required (not null)
            if (eventCode == null)
            {
                throw new ArgumentNullException("eventCode is a required property for PlayerActionLogReqDto and cannot be null");
            }
            this.EventCode = eventCode;
            // to ensure "eventData" is required (not null)
            if (eventData == null)
            {
                throw new ArgumentNullException("eventData is a required property for PlayerActionLogReqDto and cannot be null");
            }
            this.EventData = eventData;
        }

        /// <summary>
        /// Gets or Sets EventCode
        /// </summary>
        [DataMember(Name = "eventCode", IsRequired = true, EmitDefaultValue = true)]
        public string EventCode { get; set; }

        /// <summary>
        /// Gets or Sets EventData
        /// </summary>
        [DataMember(Name = "eventData", IsRequired = true, EmitDefaultValue = true)]
        public Object EventData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerActionLogReqDto {\n");
            sb.Append("  EventCode: ").Append(EventCode).Append("\n");
            sb.Append("  EventData: ").Append(EventData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
