/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// PlayerRedeemInvitationCodeReqDto
    /// </summary>
    [DataContract(Name = "PlayerRedeemInvitationCodeReqDto")]
    public partial class PlayerRedeemInvitationCodeReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRedeemInvitationCodeReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerRedeemInvitationCodeReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRedeemInvitationCodeReqDto" /> class.
        /// </summary>
        /// <param name="invitationCode">invitationCode (required).</param>
        public PlayerRedeemInvitationCodeReqDto(string invitationCode = default(string))
        {
            // to ensure "invitationCode" is required (not null)
            if (invitationCode == null)
            {
                throw new ArgumentNullException("invitationCode is a required property for PlayerRedeemInvitationCodeReqDto and cannot be null");
            }
            this.InvitationCode = invitationCode;
        }

        /// <summary>
        /// Gets or Sets InvitationCode
        /// </summary>
        [DataMember(Name = "invitationCode", IsRequired = true, EmitDefaultValue = true)]
        public string InvitationCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerRedeemInvitationCodeReqDto {\n");
            sb.Append("  InvitationCode: ").Append(InvitationCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
