/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// PublicPlayerDto
    /// </summary>
    [DataContract(Name = "PublicPlayerDto")]
    public partial class PublicPlayerDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicPlayerDto" /> class.
        /// </summary>
        /// <param name="uid">uid.</param>
        /// <param name="name">name.</param>
        /// <param name="gameData">gameData.</param>
        /// <param name="gameScore">gameScore.</param>
        /// <param name="profileData">profileData.</param>
        public PublicPlayerDto(string uid = default(string), string name = default(string), Dictionary<string, Object> gameData = default(Dictionary<string, Object>), Dictionary<string, double?> gameScore = default(Dictionary<string, double?>), Dictionary<string, string> profileData = default(Dictionary<string, string>))
        {
            this.Uid = uid;
            this.Name = name;
            this.GameData = gameData;
            this.GameScore = gameScore;
            this.ProfileData = profileData;
        }

        /// <summary>
        /// Gets or Sets Uid
        /// </summary>
        [DataMember(Name = "uid", EmitDefaultValue = false)]
        public string Uid { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets GameData
        /// </summary>
        [DataMember(Name = "gameData", EmitDefaultValue = false)]
        public Dictionary<string, Object> GameData { get; set; }

        /// <summary>
        /// Gets or Sets GameScore
        /// </summary>
        [DataMember(Name = "gameScore", EmitDefaultValue = false)]
        public Dictionary<string, double?> GameScore { get; set; }

        /// <summary>
        /// Gets or Sets ProfileData
        /// </summary>
        [DataMember(Name = "profileData", EmitDefaultValue = false)]
        public Dictionary<string, string> ProfileData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicPlayerDto {\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  GameData: ").Append(GameData).Append("\n");
            sb.Append("  GameScore: ").Append(GameScore).Append("\n");
            sb.Append("  ProfileData: ").Append(ProfileData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
