/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// QueryResponseMetadata
    /// </summary>
    [DataContract(Name = "QueryResponseMetadata")]
    public partial class QueryResponseMetadata
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryResponseMetadata" /> class.
        /// </summary>
        /// <param name="orderBy">orderBy.</param>
        /// <param name="ascending">ascending.</param>
        /// <param name="startAt">startAt.</param>
        /// <param name="startKey">startKey.</param>
        /// <param name="limit">limit.</param>
        public QueryResponseMetadata(string orderBy = default(string), bool ascending = default(bool), Object startAt = default(Object), string startKey = default(string), int? limit = default(int?))
        {
            this.OrderBy = orderBy;
            this.Ascending = ascending;
            this.StartAt = startAt;
            this.StartKey = startKey;
            this.Limit = limit;
        }

        /// <summary>
        /// Gets or Sets OrderBy
        /// </summary>
        /// <example>createdAt</example>
        [DataMember(Name = "orderBy", EmitDefaultValue = false)]
        public string OrderBy { get; set; }

        /// <summary>
        /// Gets or Sets Ascending
        /// </summary>
        /// <example>true</example>
        [DataMember(Name = "ascending", EmitDefaultValue = true)]
        public bool Ascending { get; set; }

        /// <summary>
        /// Gets or Sets StartAt
        /// </summary>
        [DataMember(Name = "startAt", EmitDefaultValue = true)]
        public Object StartAt { get; set; }

        /// <summary>
        /// Gets or Sets StartKey
        /// </summary>
        [DataMember(Name = "startKey", EmitDefaultValue = false)]
        public string StartKey { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        /// <example>100</example>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int? Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryResponseMetadata {\n");
            sb.Append("  OrderBy: ").Append(OrderBy).Append("\n");
            sb.Append("  Ascending: ").Append(Ascending).Append("\n");
            sb.Append("  StartAt: ").Append(StartAt).Append("\n");
            sb.Append("  StartKey: ").Append(StartKey).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
