/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// ReadPlayerMailsReqDto
    /// </summary>
    [DataContract(Name = "ReadPlayerMailsReqDto")]
    public partial class ReadPlayerMailsReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadPlayerMailsReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReadPlayerMailsReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadPlayerMailsReqDto" /> class.
        /// </summary>
        /// <param name="mailIds">mailIds (required).</param>
        /// <param name="receiveAllAttachments">receiveAllAttachments (required).</param>
        public ReadPlayerMailsReqDto(List<Object> mailIds = default(List<Object>), bool receiveAllAttachments = default(bool))
        {
            // to ensure "mailIds" is required (not null)
            if (mailIds == null)
            {
                throw new ArgumentNullException("mailIds is a required property for ReadPlayerMailsReqDto and cannot be null");
            }
            this.MailIds = mailIds;
            this.ReceiveAllAttachments = receiveAllAttachments;
        }

        /// <summary>
        /// Gets or Sets MailIds
        /// </summary>
        [DataMember(Name = "mailIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> MailIds { get; set; }

        /// <summary>
        /// Gets or Sets ReceiveAllAttachments
        /// </summary>
        [DataMember(Name = "receiveAllAttachments", IsRequired = true, EmitDefaultValue = true)]
        public bool ReceiveAllAttachments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadPlayerMailsReqDto {\n");
            sb.Append("  MailIds: ").Append(MailIds).Append("\n");
            sb.Append("  ReceiveAllAttachments: ").Append(ReceiveAllAttachments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
