/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// Receipt
    /// </summary>
    [DataContract(Name = "Receipt")]
    public partial class Receipt
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Receipt" /> class.
        /// </summary>
        /// <param name="originalPurchaseDatePst">originalPurchaseDatePst.</param>
        /// <param name="originalTransactionId">originalTransactionId.</param>
        /// <param name="originalPurchaseDateMs">originalPurchaseDateMs.</param>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="productId">productId.</param>
        /// <param name="bvrs">bvrs.</param>
        /// <param name="purchaseDateMs">purchaseDateMs.</param>
        /// <param name="purchaseDate">purchaseDate.</param>
        /// <param name="originalPurchaseDate">originalPurchaseDate.</param>
        /// <param name="purchaseDatePst">purchaseDatePst.</param>
        /// <param name="bid">bid.</param>
        /// <param name="itemId">itemId.</param>
        public Receipt(string originalPurchaseDatePst = default(string), string originalTransactionId = default(string), string originalPurchaseDateMs = default(string), string transactionId = default(string), string quantity = default(string), string productId = default(string), string bvrs = default(string), string purchaseDateMs = default(string), string purchaseDate = default(string), string originalPurchaseDate = default(string), string purchaseDatePst = default(string), string bid = default(string), string itemId = default(string))
        {
            this.OriginalPurchaseDatePst = originalPurchaseDatePst;
            this.OriginalTransactionId = originalTransactionId;
            this.OriginalPurchaseDateMs = originalPurchaseDateMs;
            this.TransactionId = transactionId;
            this.Quantity = quantity;
            this.ProductId = productId;
            this.Bvrs = bvrs;
            this.PurchaseDateMs = purchaseDateMs;
            this.PurchaseDate = purchaseDate;
            this.OriginalPurchaseDate = originalPurchaseDate;
            this.PurchaseDatePst = purchaseDatePst;
            this.Bid = bid;
            this.ItemId = itemId;
        }

        /// <summary>
        /// Gets or Sets OriginalPurchaseDatePst
        /// </summary>
        [DataMember(Name = "original_purchase_date_pst", EmitDefaultValue = false)]
        public string OriginalPurchaseDatePst { get; set; }

        /// <summary>
        /// Gets or Sets OriginalTransactionId
        /// </summary>
        [DataMember(Name = "original_transaction_id", EmitDefaultValue = false)]
        public string OriginalTransactionId { get; set; }

        /// <summary>
        /// Gets or Sets OriginalPurchaseDateMs
        /// </summary>
        [DataMember(Name = "original_purchase_date_ms", EmitDefaultValue = false)]
        public string OriginalPurchaseDateMs { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transaction_id", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public string Quantity { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name = "product_id", EmitDefaultValue = false)]
        public string ProductId { get; set; }

        /// <summary>
        /// Gets or Sets Bvrs
        /// </summary>
        [DataMember(Name = "bvrs", EmitDefaultValue = false)]
        public string Bvrs { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseDateMs
        /// </summary>
        [DataMember(Name = "purchase_date_ms", EmitDefaultValue = false)]
        public string PurchaseDateMs { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseDate
        /// </summary>
        [DataMember(Name = "purchase_date", EmitDefaultValue = false)]
        public string PurchaseDate { get; set; }

        /// <summary>
        /// Gets or Sets OriginalPurchaseDate
        /// </summary>
        [DataMember(Name = "original_purchase_date", EmitDefaultValue = false)]
        public string OriginalPurchaseDate { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseDatePst
        /// </summary>
        [DataMember(Name = "purchase_date_pst", EmitDefaultValue = false)]
        public string PurchaseDatePst { get; set; }

        /// <summary>
        /// Gets or Sets Bid
        /// </summary>
        [DataMember(Name = "bid", EmitDefaultValue = false)]
        public string Bid { get; set; }

        /// <summary>
        /// Gets or Sets ItemId
        /// </summary>
        [DataMember(Name = "item_id", EmitDefaultValue = false)]
        public string ItemId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Receipt {\n");
            sb.Append("  OriginalPurchaseDatePst: ").Append(OriginalPurchaseDatePst).Append("\n");
            sb.Append("  OriginalTransactionId: ").Append(OriginalTransactionId).Append("\n");
            sb.Append("  OriginalPurchaseDateMs: ").Append(OriginalPurchaseDateMs).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Bvrs: ").Append(Bvrs).Append("\n");
            sb.Append("  PurchaseDateMs: ").Append(PurchaseDateMs).Append("\n");
            sb.Append("  PurchaseDate: ").Append(PurchaseDate).Append("\n");
            sb.Append("  OriginalPurchaseDate: ").Append(OriginalPurchaseDate).Append("\n");
            sb.Append("  PurchaseDatePst: ").Append(PurchaseDatePst).Append("\n");
            sb.Append("  Bid: ").Append(Bid).Append("\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
