/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// UpdateGameDataDto
    /// </summary>
    [DataContract(Name = "UpdateGameDataDto")]
    public partial class UpdateGameDataDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGameDataDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateGameDataDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGameDataDto" /> class.
        /// </summary>
        /// <param name="pathJsonStr">pathJsonStr (required).</param>
        /// <param name="value">value (required).</param>
        public UpdateGameDataDto(string pathJsonStr = default(string), Object value = default(Object))
        {
            // to ensure "pathJsonStr" is required (not null)
            if (pathJsonStr == null)
            {
                throw new ArgumentNullException("pathJsonStr is a required property for UpdateGameDataDto and cannot be null");
            }
            this.PathJsonStr = pathJsonStr;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for UpdateGameDataDto and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets PathJsonStr
        /// </summary>
        [DataMember(Name = "pathJsonStr", IsRequired = true, EmitDefaultValue = true)]
        public string PathJsonStr { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGameDataDto {\n");
            sb.Append("  PathJsonStr: ").Append(PathJsonStr).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
