/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Alohacorp.Durian.Client.OpenAPIDateConverter;

namespace Alohacorp.Durian.Model
{
    /// <summary>
    /// VerifyAppStoreReceiptReqDto
    /// </summary>
    [DataContract(Name = "VerifyAppStoreReceiptReqDto")]
    public partial class VerifyAppStoreReceiptReqDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyAppStoreReceiptReqDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyAppStoreReceiptReqDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyAppStoreReceiptReqDto" /> class.
        /// </summary>
        /// <param name="receipt">receipt (required).</param>
        public VerifyAppStoreReceiptReqDto(string receipt = default(string))
        {
            // to ensure "receipt" is required (not null)
            if (receipt == null)
            {
                throw new ArgumentNullException("receipt is a required property for VerifyAppStoreReceiptReqDto and cannot be null");
            }
            this.Receipt = receipt;
        }

        /// <summary>
        /// Gets or Sets Receipt
        /// </summary>
        [DataMember(Name = "receipt", IsRequired = true, EmitDefaultValue = true)]
        public string Receipt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyAppStoreReceiptReqDto {\n");
            sb.Append("  Receipt: ").Append(Receipt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
