/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Alohacorp.Durian.Client;
using Alohacorp.Durian.Model;

namespace Alohacorp.Durian.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIAPApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Verify app store purchase
        /// </summary>
        /// <remarks>
        ///  Verify app store purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <returns>RootReceiptDto</returns>
        RootReceiptDto VerifyAppStorePurchase(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto);

        /// <summary>
        /// Verify app store purchase
        /// </summary>
        /// <remarks>
        ///  Verify app store purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <returns>ApiResponse of RootReceiptDto</returns>
        ApiResponse<RootReceiptDto> VerifyAppStorePurchaseWithHttpInfo(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto);
        /// <summary>
        /// Verify google play purchase
        /// </summary>
        /// <remarks>
        ///  Verify google play purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <returns>RootReceiptDto</returns>
        RootReceiptDto VerifyGooglePlayPurchase(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto);

        /// <summary>
        /// Verify google play purchase
        /// </summary>
        /// <remarks>
        ///  Verify google play purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <returns>ApiResponse of RootReceiptDto</returns>
        ApiResponse<RootReceiptDto> VerifyGooglePlayPurchaseWithHttpInfo(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIAPApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Verify app store purchase
        /// </summary>
        /// <remarks>
        ///  Verify app store purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootReceiptDto</returns>
        System.Threading.Tasks.Task<RootReceiptDto> VerifyAppStorePurchaseAsync(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Verify app store purchase
        /// </summary>
        /// <remarks>
        ///  Verify app store purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootReceiptDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootReceiptDto>> VerifyAppStorePurchaseWithHttpInfoAsync(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Verify google play purchase
        /// </summary>
        /// <remarks>
        ///  Verify google play purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootReceiptDto</returns>
        System.Threading.Tasks.Task<RootReceiptDto> VerifyGooglePlayPurchaseAsync(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Verify google play purchase
        /// </summary>
        /// <remarks>
        ///  Verify google play purchase.         
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootReceiptDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootReceiptDto>> VerifyGooglePlayPurchaseWithHttpInfoAsync(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIAPApi : IIAPApiSync, IIAPApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IAPApi : IDisposable, IIAPApi
    {
        private Alohacorp.Durian.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IAPApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public IAPApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IAPApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public IAPApi(string basePath)
        {
            this.Configuration = Alohacorp.Durian.Client.Configuration.MergeConfigurations(
                Alohacorp.Durian.Client.GlobalConfiguration.Instance,
                new Alohacorp.Durian.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Alohacorp.Durian.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IAPApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public IAPApi(Alohacorp.Durian.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Alohacorp.Durian.Client.Configuration.MergeConfigurations(
                Alohacorp.Durian.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Alohacorp.Durian.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IAPApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public IAPApi(Alohacorp.Durian.Client.ISynchronousClient client, Alohacorp.Durian.Client.IAsynchronousClient asyncClient, Alohacorp.Durian.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Alohacorp.Durian.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Alohacorp.Durian.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Alohacorp.Durian.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Alohacorp.Durian.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Alohacorp.Durian.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Verify app store purchase  Verify app store purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <returns>RootReceiptDto</returns>
        public RootReceiptDto VerifyAppStorePurchase(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto)
        {
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = VerifyAppStorePurchaseWithHttpInfo(verifyAppStoreReceiptReqDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify app store purchase  Verify app store purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <returns>ApiResponse of RootReceiptDto</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> VerifyAppStorePurchaseWithHttpInfo(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto)
        {
            // verify the required parameter 'verifyAppStoreReceiptReqDto' is set
            if (verifyAppStoreReceiptReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'verifyAppStoreReceiptReqDto' when calling IAPApi->VerifyAppStorePurchase");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = verifyAppStoreReceiptReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RootReceiptDto>($"/v1/iap/verify-receipt/app-store", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyAppStorePurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify app store purchase  Verify app store purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootReceiptDto</returns>
        public async System.Threading.Tasks.Task<RootReceiptDto> VerifyAppStorePurchaseAsync(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = VerifyAppStorePurchaseWithHttpInfoAsync(verifyAppStoreReceiptReqDto, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify app store purchase  Verify app store purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyAppStoreReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootReceiptDto)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootReceiptDto>> VerifyAppStorePurchaseWithHttpInfoAsync(VerifyAppStoreReceiptReqDto verifyAppStoreReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'verifyAppStoreReceiptReqDto' is set
            if (verifyAppStoreReceiptReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'verifyAppStoreReceiptReqDto' when calling IAPApi->VerifyAppStorePurchase");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = verifyAppStoreReceiptReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<RootReceiptDto>($"/v1/iap/verify-receipt/app-store", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyAppStorePurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify google play purchase  Verify google play purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <returns>RootReceiptDto</returns>
        public RootReceiptDto VerifyGooglePlayPurchase(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto)
        {
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = VerifyGooglePlayPurchaseWithHttpInfo(verifyGooglePlayReceiptReqDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify google play purchase  Verify google play purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <returns>ApiResponse of RootReceiptDto</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> VerifyGooglePlayPurchaseWithHttpInfo(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto)
        {
            // verify the required parameter 'verifyGooglePlayReceiptReqDto' is set
            if (verifyGooglePlayReceiptReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'verifyGooglePlayReceiptReqDto' when calling IAPApi->VerifyGooglePlayPurchase");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = verifyGooglePlayReceiptReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RootReceiptDto>($"/v1/iap/verify-receipt/google-play", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyGooglePlayPurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify google play purchase  Verify google play purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootReceiptDto</returns>
        public async System.Threading.Tasks.Task<RootReceiptDto> VerifyGooglePlayPurchaseAsync(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = VerifyGooglePlayPurchaseWithHttpInfoAsync(verifyGooglePlayReceiptReqDto, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootReceiptDto> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify google play purchase  Verify google play purchase.         
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyGooglePlayReceiptReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootReceiptDto)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootReceiptDto>> VerifyGooglePlayPurchaseWithHttpInfoAsync(VerifyGooglePlayReceiptReqDto verifyGooglePlayReceiptReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'verifyGooglePlayReceiptReqDto' is set
            if (verifyGooglePlayReceiptReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'verifyGooglePlayReceiptReqDto' when calling IAPApi->VerifyGooglePlayPurchase");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = verifyGooglePlayReceiptReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<RootReceiptDto>($"/v1/iap/verify-receipt/google-play", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyGooglePlayPurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
