/*
 * Durian API - aloha-demo
 *
 * Durian API (aloha-demo) OpenApi Documentation
 *
 * The version of the OpenAPI document: 0.4.12
 * Contact: devlopment@aloha-corp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Alohacorp.Durian.Client;
using Alohacorp.Durian.Model;

namespace Alohacorp.Durian.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMailApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a mail
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        RootVoid DeleteMail(string mailId);

        /// <summary>
        /// Delete a mail
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        ApiResponse<RootVoid> DeleteMailWithHttpInfo(string mailId);
        /// <summary>
        /// Get a mail by id
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootPlayerMailDto</returns>
        RootPlayerMailDto GetMail(string mailId);

        /// <summary>
        /// Get a mail by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootPlayerMailDto</returns>
        ApiResponse<RootPlayerMailDto> GetMailWithHttpInfo(string mailId);
        /// <summary>
        /// Get list of mails
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        RootListResponsePlayerMailDtoQueryResponseMetadata GetMails(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object));

        /// <summary>
        /// Get list of mails
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata> GetMailsWithHttpInfo(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object));
        /// <summary>
        /// Read a mail
        /// </summary>
        /// <remarks>
        ///  Mark a mail as read. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        RootVoid ReadMail(string mailId);

        /// <summary>
        /// Read a mail
        /// </summary>
        /// <remarks>
        ///  Mark a mail as read. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        ApiResponse<RootVoid> ReadMailWithHttpInfo(string mailId);
        /// <summary>
        /// Read mails
        /// </summary>
        /// <remarks>
        ///  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <returns>RootVoid</returns>
        RootVoid ReadMails(ReadPlayerMailsReqDto readPlayerMailsReqDto);

        /// <summary>
        /// Read mails
        /// </summary>
        /// <remarks>
        ///  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        ApiResponse<RootVoid> ReadMailsWithHttpInfo(ReadPlayerMailsReqDto readPlayerMailsReqDto);
        /// <summary>
        /// Receive an attachment
        /// </summary>
        /// <remarks>
        ///  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        RootVoid ReceiveAttachment(string mailId);

        /// <summary>
        /// Receive an attachment
        /// </summary>
        /// <remarks>
        ///  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        ApiResponse<RootVoid> ReceiveAttachmentWithHttpInfo(string mailId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMailApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete a mail
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        System.Threading.Tasks.Task<RootVoid> DeleteMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a mail
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootVoid>> DeleteMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get a mail by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootPlayerMailDto</returns>
        System.Threading.Tasks.Task<RootPlayerMailDto> GetMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a mail by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootPlayerMailDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootPlayerMailDto>> GetMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get list of mails
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        System.Threading.Tasks.Task<RootListResponsePlayerMailDtoQueryResponseMetadata> GetMailsAsync(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get list of mails
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootListResponsePlayerMailDtoQueryResponseMetadata)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata>> GetMailsWithHttpInfoAsync(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Read a mail
        /// </summary>
        /// <remarks>
        ///  Mark a mail as read. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        System.Threading.Tasks.Task<RootVoid> ReadMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Read a mail
        /// </summary>
        /// <remarks>
        ///  Mark a mail as read. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootVoid>> ReadMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Read mails
        /// </summary>
        /// <remarks>
        ///  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        System.Threading.Tasks.Task<RootVoid> ReadMailsAsync(ReadPlayerMailsReqDto readPlayerMailsReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Read mails
        /// </summary>
        /// <remarks>
        ///  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootVoid>> ReadMailsWithHttpInfoAsync(ReadPlayerMailsReqDto readPlayerMailsReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Receive an attachment
        /// </summary>
        /// <remarks>
        ///  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        System.Threading.Tasks.Task<RootVoid> ReceiveAttachmentAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Receive an attachment
        /// </summary>
        /// <remarks>
        ///  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </remarks>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        System.Threading.Tasks.Task<ApiResponse<RootVoid>> ReceiveAttachmentWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMailApi : IMailApiSync, IMailApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MailApi : IDisposable, IMailApi
    {
        private Alohacorp.Durian.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MailApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MailApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MailApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MailApi(string basePath)
        {
            this.Configuration = Alohacorp.Durian.Client.Configuration.MergeConfigurations(
                Alohacorp.Durian.Client.GlobalConfiguration.Instance,
                new Alohacorp.Durian.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Alohacorp.Durian.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MailApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MailApi(Alohacorp.Durian.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Alohacorp.Durian.Client.Configuration.MergeConfigurations(
                Alohacorp.Durian.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Alohacorp.Durian.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MailApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MailApi(Alohacorp.Durian.Client.ISynchronousClient client, Alohacorp.Durian.Client.IAsynchronousClient asyncClient, Alohacorp.Durian.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Alohacorp.Durian.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Alohacorp.Durian.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Alohacorp.Durian.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Alohacorp.Durian.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Alohacorp.Durian.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Alohacorp.Durian.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete a mail 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        public RootVoid DeleteMail(string mailId)
        {
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = DeleteMailWithHttpInfo(mailId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a mail 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootVoid> DeleteMailWithHttpInfo(string mailId)
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->DeleteMail");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<RootVoid>($"/v1/mails/{mailId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a mail 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        public async System.Threading.Tasks.Task<RootVoid> DeleteMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = DeleteMailWithHttpInfoAsync(mailId, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a mail 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootVoid>> DeleteMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->DeleteMail");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.DeleteAsync<RootVoid>($"/v1/mails/{mailId}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a mail by id 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootPlayerMailDto</returns>
        public RootPlayerMailDto GetMail(string mailId)
        {
            Alohacorp.Durian.Client.ApiResponse<RootPlayerMailDto> localVarResponse = GetMailWithHttpInfo(mailId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a mail by id 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootPlayerMailDto</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootPlayerMailDto> GetMailWithHttpInfo(string mailId)
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->GetMail");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<RootPlayerMailDto>($"/v1/mails/{mailId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a mail by id 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootPlayerMailDto</returns>
        public async System.Threading.Tasks.Task<RootPlayerMailDto> GetMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetMailWithHttpInfoAsync(mailId, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootPlayerMailDto> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootPlayerMailDto> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a mail by id 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootPlayerMailDto)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootPlayerMailDto>> GetMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->GetMail");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<RootPlayerMailDto>($"/v1/mails/{mailId}", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get list of mails 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        public RootListResponsePlayerMailDtoQueryResponseMetadata GetMails(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object))
        {
            Alohacorp.Durian.Client.ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata> localVarResponse = GetMailsWithHttpInfo(orderBy, ascending, startAt, endAt, startKey, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of mails 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata> GetMailsWithHttpInfo(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object))
        {
            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (ascending != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "ascending", ascending));
            }
            if (startAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "startAt", startAt));
            }
            if (endAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "endAt", endAt));
            }
            if (startKey != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "startKey", startKey));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<RootListResponsePlayerMailDtoQueryResponseMetadata>($"/v1/mails", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMails", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get list of mails 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootListResponsePlayerMailDtoQueryResponseMetadata</returns>
        public async System.Threading.Tasks.Task<RootListResponsePlayerMailDtoQueryResponseMetadata> GetMailsAsync(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetMailsWithHttpInfoAsync(orderBy, ascending, startAt, endAt, startKey, limit, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of mails 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="ascending"> (optional)</param>
        /// <param name="startAt"> (optional)</param>
        /// <param name="endAt"> (optional)</param>
        /// <param name="startKey"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootListResponsePlayerMailDtoQueryResponseMetadata)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootListResponsePlayerMailDtoQueryResponseMetadata>> GetMailsWithHttpInfoAsync(Object orderBy = default(Object), Object ascending = default(Object), Object startAt = default(Object), Object endAt = default(Object), Object startKey = default(Object), Object limit = default(Object), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (ascending != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "ascending", ascending));
            }
            if (startAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "startAt", startAt));
            }
            if (endAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "endAt", endAt));
            }
            if (startKey != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "startKey", startKey));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Alohacorp.Durian.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<RootListResponsePlayerMailDtoQueryResponseMetadata>($"/v1/mails", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMails", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read a mail  Mark a mail as read. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        public RootVoid ReadMail(string mailId)
        {
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = ReadMailWithHttpInfo(mailId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read a mail  Mark a mail as read. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootVoid> ReadMailWithHttpInfo(string mailId)
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->ReadMail");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<RootVoid>($"/v1/mails/{mailId}/read", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read a mail  Mark a mail as read. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        public async System.Threading.Tasks.Task<RootVoid> ReadMailAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ReadMailWithHttpInfoAsync(mailId, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read a mail  Mark a mail as read. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootVoid>> ReadMailWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->ReadMail");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<RootVoid>($"/v1/mails/{mailId}/read", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadMail", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read mails  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <returns>RootVoid</returns>
        public RootVoid ReadMails(ReadPlayerMailsReqDto readPlayerMailsReqDto)
        {
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = ReadMailsWithHttpInfo(readPlayerMailsReqDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read mails  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootVoid> ReadMailsWithHttpInfo(ReadPlayerMailsReqDto readPlayerMailsReqDto)
        {
            // verify the required parameter 'readPlayerMailsReqDto' is set
            if (readPlayerMailsReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'readPlayerMailsReqDto' when calling MailApi->ReadMails");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = readPlayerMailsReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<RootVoid>($"/v1/mails", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadMails", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read mails  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        public async System.Threading.Tasks.Task<RootVoid> ReadMailsAsync(ReadPlayerMailsReqDto readPlayerMailsReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ReadMailsWithHttpInfoAsync(readPlayerMailsReqDto, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read mails  Mark mails as read. - &#x60;mailIds&#x60; is a list of mail ids to mark as read. - &#x60;receiveAllAttachments&#x60; is a boolean value to mark all attachments as received. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="readPlayerMailsReqDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootVoid>> ReadMailsWithHttpInfoAsync(ReadPlayerMailsReqDto readPlayerMailsReqDto, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'readPlayerMailsReqDto' is set
            if (readPlayerMailsReqDto == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'readPlayerMailsReqDto' when calling MailApi->ReadMails");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = readPlayerMailsReqDto;

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<RootVoid>($"/v1/mails", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadMails", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Receive an attachment  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>RootVoid</returns>
        public RootVoid ReceiveAttachment(string mailId)
        {
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = ReceiveAttachmentWithHttpInfo(mailId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Receive an attachment  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <returns>ApiResponse of RootVoid</returns>
        public Alohacorp.Durian.Client.ApiResponse<RootVoid> ReceiveAttachmentWithHttpInfo(string mailId)
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->ReceiveAttachment");

            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<RootVoid>($"/v1/mails/{mailId}/receive-attachment", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReceiveAttachment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Receive an attachment  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RootVoid</returns>
        public async System.Threading.Tasks.Task<RootVoid> ReceiveAttachmentAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ReceiveAttachmentWithHttpInfoAsync(mailId, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task.ConfigureAwait(false);
#else
            Alohacorp.Durian.Client.ApiResponse<RootVoid> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        /// Receive an attachment  Mark an attachment as received. - &#x60;attachmentIdx&#x60; is the index of the attachment in the attachments list of the mail which starts from 0. 
        /// </summary>
        /// <exception cref="Alohacorp.Durian.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RootVoid)</returns>
        public async System.Threading.Tasks.Task<Alohacorp.Durian.Client.ApiResponse<RootVoid>> ReceiveAttachmentWithHttpInfoAsync(string mailId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'mailId' is set
            if (mailId == null)
                throw new Alohacorp.Durian.Client.ApiException(400, "Missing required parameter 'mailId' when calling MailApi->ReceiveAttachment");


            Alohacorp.Durian.Client.RequestOptions localVarRequestOptions = new Alohacorp.Durian.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Alohacorp.Durian.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Alohacorp.Durian.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("mailId", Alohacorp.Durian.Client.ClientUtils.ParameterToString(mailId)); // path parameter

            // authentication (firebaseAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PutAsync<RootVoid>($"/v1/mails/{mailId}/receive-attachment", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReceiveAttachment", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
