name: Loxops - AI Code Review Assistant

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Code Review Assistant
        uses: AlohaFactory-Dev/loxops@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          project-type: 'unity'
          file-extensions: '.ts,.js,.tsx,.jsx,.cs,.java,.kt,.xml,.json,.yaml,.yml'
          exclude-patterns: 'node_modules/**,dist/**,build/**,*.min.js,*.test.*'
          find-related-files: 'true'
          max-files: '10'
          model: 'claude-3-7-sonnet-20250219'
          use-repomix: 'true'
